[workspace]
authors = ["Joshua Siraj <joshua.siraj@uhn.ca>"]
channels = ["conda-forge", "pytorch"] 
name = "medsam2_inference"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.12"
pytorch-cuda = "==12.4"


[pypi-dependencies]
MedSAM2 = { path = "src/medsam2_runner/MedSAM2", editable = true, extras = ["dev"] }
simpleitk = ">=2.5.2, <3"
pydantic = ">=2.11.7, <3"

